### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [seilarmoon/Prework#1]
Thanks for submitting your pre-work, but your current submission is incomplete. Your ezGIF has expired and is not rendering on our end.

Please review the [prework submission checklist](https://courses.codepath.org/snippets/ios_university/prework.md#heading-submission-checklist) to complete the missing features. Please re-submit your project on your [application dashboard](https://apply.codepath.org/dashboard/), and it will notify us to review again.

**Comment by seilarmoon** [comment]
This is done, thank you. Hopefully it works now!
